included:
    - MockApp/Sources
    - MockAppTests

disabled_rules:
- trailing_whitespace

identifier_name:
  excluded:
    - id

function_body_length:
- 15 # warning
- 20 # error

file_length:
- 100 # warning
- 150 # error

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4
